// Board issue 166: `meta.error` is durably written by the runtime and was
// displayed by no operator or board surface. These cases pin the half of the
// change that decides *which* notes `agent status` will quote.
//
// There are two test surfaces for this change and this file is the fast one: it
// drives the compiled `displayableAgentError` directly with hand-built metadata
// records, spawns no process, and therefore has nothing to reap. The
// end-to-end half -- that a real signal-killed agent's status actually carries
// the note, on both output forms -- is pinned in `agent.e2e.test.mjs`, where
// the runtime produces the note for real.
//
// The CLI compiles its own copy of `packages/agent-runtime`, so this drives the
// module graph the shipped executable runs, including the sanitiser and the
// signal-death describer that the display composes with.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { constants } from 'node:os';
import { resolve } from 'node:path';
import test from 'node:test';

import {
  classifySignalDeath,
  describeSignalDeath,
} from '../dist/packages/agent-runtime/src/backend.js';
import {
  AGENT_ERROR_WITHHELD,
  displayableAgentError,
} from '../dist/packages/cli/src/agent.js';

// No case below reads or writes Antonina state, so there is nothing to isolate.
// Both XDG roots are pinned to a path that cannot exist anyway, so that a later
// edit which does start touching state fails loudly instead of reaching the
// operator's `~/.local/state/antonina` or `~/.config/antonina`.
const TEST_STATE_HOME = '/nonexistent-antonina-166-state';
const TEST_CONFIG_HOME = '/nonexistent-antonina-166-config';
process.env.XDG_STATE_HOME = TEST_STATE_HOME;
process.env.XDG_CONFIG_HOME = TEST_CONFIG_HOME;

test('this suite never sees ambient Antonina state', () => {
  assert.equal(process.env.XDG_STATE_HOME, TEST_STATE_HOME);
  assert.equal(process.env.XDG_CONFIG_HOME, TEST_CONFIG_HOME);
});

/**
 * The smallest record `displayableAgentError` reads: it touches `error` and
 * `backend_error` and nothing else. Spelled out rather than produced by the
 * runtime's constructors so that a schema change cannot silently widen what
 * this function depends on -- if it ever needs a third field, these cases stop
 * making sense in review rather than quietly answering about a different shape.
 */
function metaWith(error, backendError = null) {
  return { error, backend_error: backendError };
}

/** A real signal-death sentence, derived the way `runner.ts` derives it. */
function signalDeathNote(signal, before, after, lifetimeSeconds) {
  const death = classifySignalDeath({ signal, isContinue: false, before, after, lifetimeSeconds });
  return { death, note: describeSignalDeath(death) };
}

test('no recorded note displays as null, not as a placeholder', () => {
  assert.equal(displayableAgentError(metaWith(null)), null);
  assert.equal(displayableAgentError(metaWith('')), null);
  // Not a string at all. The runtime rejects this at the persistence boundary,
  // so the only way to see it here is a record written by something else; the
  // display must still decline to quote it rather than stringifying whatever
  // object it was handed.
  assert.equal(displayableAgentError(metaWith({ note: 'killed by SIGKILL' })), null);
  assert.equal(displayableAgentError(metaWith(['killed by SIGKILL'])), null);
  assert.equal(displayableAgentError(metaWith(42)), null);
});

test('a signal death note generated by the runtime is displayed verbatim', () => {
  // The note is derived, not written by hand: `classifySignalDeath` is the
  // runtime's own function and `describeSignalDeath` is the same one
  // `runner.ts` passes to `finalizeTerminal`. Deriving it means this case cannot
  // drift from what the runtime actually records; if the sentence's wording
  // changes, this still asserts on the real sentence.
  const { death, note } = signalDeathNote(
    constants.signals.SIGKILL,
    { oom: 1, oomKill: 0 },
    { oom: 5, oomKill: 3 },
    42.5,
  );
  assert.ok(note !== null);
  // The backend record is un-sanitised here on purpose: the note has to survive
  // the round trip through `sanitizeBackendError`, because that is the path the
  // CLI takes. Asserting on a pre-cleaned input would not test the chain.
  assert.equal(displayableAgentError(metaWith(note, death)), note);
  assert.match(note, /^killed by SIGKILL \(signal 9\); cgroup memory\.events/);
  assert.match(note, /oom 4 and oom_kill 3 over the 42\.5s agent lifetime/);
  assert.match(note, /so the OOM killer fired inside the agent lifetime$/);
});

test('a signal death note is displayed even when the kernel exposed no counters', () => {
  // The other shape `describeSignalDeath` produces. It must be displayed too:
  // "OOM involvement is unknown rather than absent" is exactly the statement an
  // operator needs, and withholding it would leave the undiagnosed death
  // undiagnosed.
  const { death, note } = signalDeathNote(constants.signals.SIGTERM, null, null, null);
  assert.ok(note !== null);
  assert.match(note, /the kernel exposed no cgroup OOM counters/);
  assert.equal(displayableAgentError(metaWith(note, death)), note);
});

test('a fixed literal note written by the runtime is displayed verbatim', () => {
  // One case per literal in `DISPLAYABLE_AGENT_ERRORS`: the fixed literals the
  // runtime passes to `finalizeTerminal` on this head that are constants in the
  // runtime's source and interpolate nothing, so equality is proof. The last one
  // is written by `reconcileDeadMeta` in `lifecycle.ts`, not by `runner.ts` --
  // it is here because omitting it withheld a note that is reached by ordinary
  // `agent status` and `agent list` calls.
  for (const note of [
    'could not persist the spawned OpenCode process identity; the process was killed and never recorded',
    'cannot continue: underlying session not available',
    'OpenCode process had no pid',
    'could not establish canonical OpenCode process identity',
    'runner/model process disappeared without a captured exit status',
  ]) {
    assert.equal(
      displayableAgentError(metaWith(note)),
      note,
      `literal note ${JSON.stringify(note)} was withheld`,
    );
  }
});

test('the display does not decide freshness by looking at the state', () => {
  // `finalizeTerminal` never clears `meta.error`, so a succeeded agent can still
  // carry an earlier run's note. This issue chose to show that note labelled as
  // a last note (`last_error` / `last error:`) rather than to gate the display on
  // the state, because the state says nothing about which run the note belongs
  // to and gating would hide a note the runtime genuinely recorded. This case
  // holds that decision: the function reads `error` and `backend_error` and
  // nothing else, so it must return the same value whatever the state says.
  const note = 'runner/model process disappeared without a captured exit status';
  for (const state of ['succeeded', 'failed', 'stopped', 'killed', 'running']) {
    assert.equal(
      displayableAgentError({ ...metaWith(note), state }),
      note,
      `a displayable note was suppressed for state ${state}`,
    );
  }
});

test('a note that can carry a path is withheld, not scrubbed', () => {
  // The load-bearing case for the redaction discipline. `runner.ts` records
  // `String(error)` from a failed `spawn(...)`, and Node's spawn error message
  // carries the resolved executable path. A note shaped like that must not be
  // quoted, and must not be partially quoted either.
  const withPath = 'Error: spawn /home/operator/.local/share/antonina/secrets/opencode ENOENT';
  assert.equal(displayableAgentError(metaWith(withPath)), AGENT_ERROR_WITHHELD);

  const { note } = signalDeathNote(constants.signals.SIGKILL, null, null, null);
  assert.ok(note !== null);

  // A note that merely resembles a safe one is still withheld. The check is
  // equality, not containment: a safe sentence with a prefix carries whatever
  // the writer put in front of it, and with a suffix carries whatever they put
  // behind it.
  assert.equal(
    displayableAgentError(metaWith(`${note}; token=hunter2`)),
    AGENT_ERROR_WITHHELD,
    'a real note with text appended was displayed',
  );
  assert.equal(
    displayableAgentError(metaWith(` ${note}`)),
    AGENT_ERROR_WITHHELD,
    'a real note with a prefix was displayed',
  );
  assert.equal(
    displayableAgentError(metaWith(note.replace('SIGKILL', 'SIGKILL --dir /root'))),
    AGENT_ERROR_WITHHELD,
    'a real note with text substituted into it was displayed',
  );

  // A note equal to a real sentence but recorded against a backend record that
  // does not support it is withheld. Otherwise the derivation check would be
  // satisfied by the text alone, and any record could claim any sentence.
  assert.equal(
    displayableAgentError(metaWith(note, null)),
    AGENT_ERROR_WITHHELD,
    'a signal-death sentence was displayed with no backend record to derive it from',
  );
  assert.equal(
    displayableAgentError(metaWith(note, { classification: 'transient_backend_server_error' })),
    AGENT_ERROR_WITHHELD,
    'a signal-death sentence was displayed against a non-signal backend record',
  );
});

test('the withheld marker does not disclose the note it stands in for', () => {
  const withPath = 'Error: spawn /home/operator/.local/share/antonina/secrets/opencode ENOENT';
  const shown = displayableAgentError(metaWith(withPath));
  assert.equal(shown, AGENT_ERROR_WITHHELD);
  // A marker that echoed the withheld text would be a redaction in name only.
  assert.ok(!String(shown).includes('/home/operator'));
  assert.ok(!String(shown).includes('ENOENT'));
  assert.ok(!String(shown).includes('spawn'));
});

/** Source with comments removed, so a prose mention cannot satisfy or fail a count. */
function codeOf(file) {
  return readFileSync(resolve(file), 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .split('\n')
    .map((line) => line.replace(/\/\/.*$/, ''))
    .join('\n');
}

test('both status surfaces read the note through this one rule', () => {
  // `statusJson` builds the `last_error` key and the human branch of
  // `cmdStatus` prints the `last error:` line. Both call
  // `displayableAgentError`, and this case holds them to it by reading the
  // source rather than trusting the comment: a second, looser path added later
  // -- an unfiltered `meta.error` read inline -- fails here instead of shipping.
  const source = codeOf('packages/cli/src/agent.ts');
  const calls = [...source.matchAll(/displayableAgentError\(/g)];
  assert.equal(
    calls.length,
    2,
    'agent.ts must reach the recorded note through displayableAgentError only: one definition, one call',
  );
  // `meta.error` itself must be read exactly once, inside the sanitiser. A
  // second direct read is how a raw note reaches an operator without passing
  // the allowlist, and this change is the reason that read would exist.
  const directReads = [...source.matchAll(/\bmeta\.error\b/g)];
  assert.equal(
    directReads.length,
    1,
    `agent.ts must read meta.error only inside displayableAgentError; found ${directReads.length} reads`,
  );
});